apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dyndns.fullname" . }}
  labels:
    {{- include "dyndns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dyndns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dyndns.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "dyndns.fullname" . }}-config
            - secretRef:
                name: {{ include "dyndns.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }} 
