apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dyndns.fullname" . }}-secret
  labels:
    {{- include "dyndns.labels" . | nindent 4 }}
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.secret.cloudflareApiToken | quote }} 
